### ISSUE TITLE
File System Support

### ISSUE THREAD

**Issue by drkleena** [minrk/thebelab#81]
Fantastic implementation, this is exactly what I have been looking for!

I am just wondering, is it possible to access particular files from the runnable code snippets?
For instance, I would like to be able to open a csv file in a runnable snippet in order to perform data visualisation. 

Thanks!

**Comment by nthiery** [comment]
Hi @drkleena!

>    I am just wondering, is it possible to access particular files
>    from the runnable code snippets? For instance, I would like to be
>    able to open a csv file in a runnable snippet in order to perform
>    data visualisation.

The snippets can access exactly those files that the Jupyter kernel
can access.

For example, if you configure thebelab to use your own jupyter server,
then you can put your files so that they are accessible by this
server. If instead you use binder as kernel provider, then you can
either access data available publicly on the web, or configure
thebelab to use a binder-enabled git repository (typically of your
own) that holds those data files.

Hope this helps!

**Comment by drkleena** [comment]
@nthiery Thanks for the speedy reply!
